version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    ports:
      - "4200:80"
    restart: on-failure
    networks:
      - home-insurance
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: .dockerfile
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - home-insurance
    depends_on:
      - mysql-db
    links: 
      - mysql-db

  mysql-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=insurance
      - MYSQL_ROOT_PASSWORD=password
      - ACCEPT_EULA=Y
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"
    networks:
      - home-insurance

networks:
  home-insurance:
    driver: bridge

# c:/temp/docker